pd.set_option('display.max_columns', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
pd.set_option("display.max_colwidth", None)
pd.set_option('display.max_rows', 500)
pd.set_option("display.max_colwidth", None)
